package avada.media.myhouse24_client.model.systemSettings.extra;

public enum Permission {

    STATISTICS,
    TRANSACTIONS,
    INVOICES,
    ACCOUNTS,
    FLATS,
    USERS,
    BUILDINGS,
    MESSAGES,
    MASTER_REQUESTS,
    COUNTERS,
    WEBSITE_CONTROL,
    SYSTEM_SETTINGS_SERVICES,
    SYSTEM_SETTINGS_TARIFFS,
    SYSTEM_SETTINGS_ROLES,
    SYSTEM_SETTINGS_STAFF,
    SYSTEM_SETTINGS_PAYMENT_DETAILS,
    SYSTEM_SETTINGS_TRANSACTION_PURPOSES

}